### ISSUE TITLE
Nicht nur Bauteile sondern auch Themen?

### ISSUE THREAD

**Issue by elektroschule** [tbs1-bo/hardware-101#3]
Damit nicht zu jedem Bauteil alle grundlegenden Informationen wiederholt werden müssen, habe ich einen Vorschlag.
Ähnlich wie die Bauteile könnten Grundlagen zu bauteilunabhängigen Themen dargestellt werden. 

Beispiele:
* GPIO (Eigenschaften, Bibliotheken, Beispiel für Input, Beispiel für Output)
* I²C (Grundlagen, Beispielschaltung, Tools, Bibliotheken)
* SPI (Grundlagen, Beispielschaltung, Tools, Bibliotheken)
* ...

In den Bauteilbeschreibungen kann darauf dann verwiesen werden.

Vielleicht kann man dabei dann auch Strategien beschreiben, um sich systematisch unbekannte Bauteile zu erarbeiten.

**Comment by pintman** [comment]
Die Idee klingt gut. :)

Ich frage mich nur, inwiefern wir hier das Rad neu erfinden. Wäre es
nicht besser auf gute bestehende Quellen zu verlinken? Oder gibt es da
nichts, was wir empfehlen könnten? Ich kann mich sogar daran erinnern,
in einem der Datenblätter eine kurze Einführung in I²C gefunden zu haben. :)

Trotzdem ist es gut, eine solche Quellensammlung oder auch gerne kurze
Beschreibungen zu haben, auf die wir verlinken können. Das könnten wir
z.B. im ITA-Wiki machen.

**Comment by elektroschule** [comment]
Geeignete Quellen können und sollten natürlich angegeben oder zitiert werden. Ziel sollte es aber trotzdem sein den Einstieg in das Thema zu vereinfachen. 
Beispiel: Für die Verwendung des I²C-Bus am Raspberry Pi ist es erstmal nicht notwendig die Signalverläufe nachzuvollziehen und zu verstehen. Es ist aber wichtig zu wissen welche Signalleitungen zum Bussystem gehören.

Ich würde zu einem Thema zunächst möglichst allgemeingültige Informationen angeben und weiter hinten erst auf Spezial- und Sonderfälle eingehen.

Wie wollen wir solche Themen im Repo integrieren?
Mein Vorschlag wäre einen Ordner "Allgemeines" anzulegen und darin dann einzelne Markdown Dateien zu den verschieden Themen: i2c.md, spi.md, gpio.md, ....
Alternative: Für jedes Thema ein Ordner und darin dann eine README.md

**Comment by pintman** [comment]
Das könnte sich durch das Physical-Computing Skript als erledigt bzw. umgesetzt herausstellen - zumindest für einige der genannten Themen.

**Comment by elektroschule** [comment]
> Das könnte sich durch das Physical-Computing Skript als erledigt bzw. umgesetzt herausstellen - zumindest für einige der genannten Themen.

Stimmt. :)
