### ISSUE TITLE
Fritzing-Dateien unkomprimiert ablegen?

### ISSUE THREAD

**Issue by pintman** [tbs1-bo/hardware-101#4]
Mit Fritzing können die Dateien auch als unkomprimierte Version mit der Endung fz statt fzz abgelegt werden.

- Vorteil: Änderungen lassen sich in git nachvollziehen, da es eine Textdatei ist.
- Nachteil: die Dateien werden natürlich größer.

Wäre es besser, auf die unkomprimierte Version umzustellen?

Die EAGLE-Dateien liegen übrigens auch bereits in dieser unkomprimierten Form vor.

**Comment by elektroschule** [comment]
Wenn ich das richtig sehe sind die .fzz-Dateien komprimierte Archive in denen die .fz-Dateien (Textdatei) liegen. Scheinbar liegen in den Archiven aber manchmal auch andere Dateien. In meinem Fall ist es der Portexpander, der nicht in den "Standardbibliotheken" enthalten ist. Das ist eine Textdatei (xml) und ein paar .svg-Dateien.

Daher würde ich wahrscheinlich lieber die .fzz Dateien im Repo ablegen.

Bei EAGLE gibt es keine Grafiken, die mitgeliefert werden müssen, daher genügt die Textdatei.
Ich weiß auch nicht, ob es ein wirklich nützlicher Vorteil ist, wenn man die Änderungen im XML-code nachvollziehen kann.

**Comment by pintman** [comment]
> Ich weiß auch nicht, ob es ein wirklich nützlicher Vorteil ist, wenn man
> die Änderungen im XML-code nachvollziehen kann.

Meist finden eh nicht so viele Änderungen an den Dateien statt. Daher
hast du vermutlich recht und wir belassen wie gehabt.
