### ISSUE TITLE
Logo for hardware 101

### ISSUE THREAD

**Issue by pintman** [tbs1-bo/hardware-101#6]
Create a Logo for the hardware 101 project.

**Comment by kylejohnston** [comment]
I'd like to help. A few questions:

1. Do you have any colors in mind for your logo?
2. Would you like a symbol or a logotype?

> Symbol: A more abstract illustration with your company name typeset alongside (e.g. Ferrari, HP, Mc Donald's, Nike, Lucent)
> Logotype: This incorporates your company name into the logo itself (e.g. Ford, IBM, Microsoft)

3. Are there any nuances of spelling that I should take into account with the wording? (i.e.. all capital letters vs sentence case)
4. Do you have any preferred choice for typeface?
5. Are there any examples of logos that you like or dislike?

**Comment by benjaminchazelle** [comment]
Here is my proposal 😃  

![image](https://user-images.githubusercontent.com/15939384/31683621-c46a166e-b37d-11e7-81a3-a4641c29b80f.png)

**Comment by pintman** [comment]
Thanks for your support and the logo. It looks quite well. :)
